AWSTemplateFormatVersion: '2010-09-09'
Description: 'WAF Configuration for Warehouse UI'

Parameters:
  Environment:
    Type: String
    Default: test
    Description: Environment name
    AllowedValues:
      - test
      - staging
      - production
  
  RateLimit:
    Type: Number
    Default: 2000
    Description: Rate limit per IP address
    MinValue: 100
    MaxValue: 20000

Resources:
  WebACL:
    Type: 'AWS::WAFv2::WebACL'
    Properties:
      Name: !Sub '${Environment}-warehouse-ui-acl'
      Description: 'Web ACL for Warehouse UI'
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub '${Environment}-WebACL'
      Rules:
        - Name: 'RateLimit'
          Priority: 1
          Statement:
            RateBasedStatement:
              Limit: !Ref RateLimit
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitRule

Outputs:
  WebACLId:
    Description: 'ID of the Web ACL'
    Value: !Ref WebACL
    Export:
      Name: !Sub '${AWS::StackName}-web-acl-id'

  WebACLArn:
    Description: 'ARN of the Web ACL'
    Value: !GetAtt WebACL.Arn
    Export:
      Name: !Sub '${AWS::StackName}-web-acl-arn'