AWSTemplateFormatVersion: '2010-09-09'
Description: Core Infrastructure for CoolRoom API

Parameters:
  Environment:
    Type: String
    Default: test
    Description: Environment name (test, staging, prod)
    AllowedValues:
      - test
      - staging
      - prod

Resources:
  # API Gateway
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "coolroom-api-${Environment}"
      Description: "CoolRoom API"
      EndpointConfiguration:
        Types:
          - REGIONAL
      ApiKeySourceType: HEADER

  # Root Method (OPTIONS for CORS)
  RootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !GetAtt ApiGateway.RootResourceId
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET,POST,PUT,DELETE'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # Base API Deployment
  BaseDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: RootMethod
    Properties:
      RestApiId: !Ref ApiGateway
      Description: !Sub "Base deployment for ${Environment} environment"
      StageName: !Ref Environment

Outputs:
  ApiGatewayId:
    Description: ID of the API Gateway REST API
    Value: !Ref ApiGateway
    Export:
      Name: !Sub "${AWS::StackName}-api-gateway-id"

  ApiGatewayRootResourceId:
    Description: ID of the API Gateway root resource
    Value: !GetAtt ApiGateway.RootResourceId
    Export:
      Name: !Sub "${AWS::StackName}-root-resource-id"

  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
    Export:
      Name: !Sub "${AWS::StackName}-api-endpoint"