AWSTemplateFormatVersion: '2010-09-09'
Description: Policies for Warehouse UI Test Environment

Parameters:
  Environment:
    Type: String
    Default: test
    Description: Environment name (e.g., test, prod)
  S3BucketName:
    Type: String
    Description: Name of the content S3 bucket
  CloudFrontOAI:
    Type: String
    Description: CloudFront Origin Access Identity ID
  CloudFrontDistributionArn:
    Type: String
    Description: ARN of the CloudFront distribution

Resources:
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontOAIAccess
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${S3BucketName}/*'
          - Sid: AllowCloudFrontLogging
            Effect: Allow
            Principal:
              Service: 'cloudfront.amazonaws.com'
            Action: 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::${S3BucketName}/cloudfront-logs/*'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Ref CloudFrontDistributionArn

Outputs:
  BucketPolicyArn:
    Description: ARN of the bucket policy
    Value: !Sub 'arn:aws:s3:::${S3BucketName}/policy'
    Export:
      Name: !Sub ${AWS::StackName}-BucketPolicyArn