AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Configuration for Warehouse UI Test Environment with improved cleanup

Parameters:
  Environment:
    Type: String
    Default: test
    Description: Environment name (e.g., test, prod)
  Timestamp:
    Type: String
    Description: Timestamp for unique bucket names
    Default: default

Resources:
  LoggingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Sub test-warehouse-ui-logs-${Environment}-${Timestamp}
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false  # Allow CloudFront to write logs
        BlockPublicPolicy: true
        IgnorePublicAcls: false # Allow CloudFront to write logs
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAllObjects
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 90
            NoncurrentVersionExpiration:
              NoncurrentDays: 1

  TestBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Sub test-warehouse-ui-content-${Environment}-${Timestamp}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: "cdn/"
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAllObjects
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 1
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  TestBucketName:
    Description: Name of the S3 bucket for test content
    Value: !Ref TestBucket
    Export:
      Name: !Sub ${AWS::StackName}-TestBucketName
  
  TestBucketDomainName:
    Description: Domain name of the S3 bucket for test content
    Value: !GetAtt TestBucket.DomainName
    Export:
      Name: !Sub ${AWS::StackName}-TestBucketDomainName

  LoggingBucketName:
    Description: Name of the S3 bucket for logs
    Value: !Ref LoggingBucket
    Export:
      Name: !Sub ${AWS::StackName}-LoggingBucketName